
using Revise

using Test

using Pkg
Pkg.activate(".")
using SPECreader


speceq = SPECEquilibrium("testing/data/G3V02L1Fi.001.sp.h5")



#= Points generated by SPEC MATLAB routines =#
@testset "Test 2 volume 1 RZ" begin
    RZ = (10.516846229475158, 0.0)
    @test all(get_RZ(0.0,0.0,0.0,speceq,1) .≈ RZ)

    RZ = (10.440759283531808, -0.207787879957446)
    get_RZ(0.2,0.3,0.4,speceq,1)
    @test all(get_RZ(0.2,0.3,0.4,speceq,1) .≈ RZ)

    RZ = (10.341652488625433, 0.146606922938160)
    @test all(get_RZ(-0.2,-0.3,-0.4,speceq,1) .≈ RZ)

    RZ = (9.762509713195801, 0.081081143963634)
    @test all(get_RZ(0.5,Float64(pi),pi/2,speceq,1) .≈ RZ)
end


@testset "Test 2 volume 2 RZ" begin
    RZ = (11.049257355316703, 0.0)
    @test all(get_RZ(0.0,0.0,0.0,speceq,2) .≈ RZ)
    
    RZ = (10.810081866694997, -0.457873079449074)
    @test all(get_RZ(0.2,0.3,0.4,speceq,2) .≈ RZ)
    
    RZ = (10.753560117266641, 0.415091414536383)
    @test all(get_RZ(-0.2,-0.3,-0.4,speceq,2) .≈ RZ)
    
    RZ = (9.158173277170803, 0.217155229782964)
    @test all(get_RZ(0.5,Float64(pi),pi/2,speceq,2) .≈ RZ)
end





@testset "Test 1 volume 1 B" begin
    B = (0.0, 0.009982177500531, 0.047523944962502)
    @test all(get_Bfield(0.0,0.0,0.0,speceq) .≈ B)

    B = (0.003951746152245, 0.016523501939107, 0.057988904019731)
    @test all(get_Bfield(0.2,0.3,0.4,speceq) .≈ B)

    B = (-0.003467844788882, 0.010851040150705, 0.038687670421183)
    @test all(get_Bfield(-0.2,-0.3,-0.4,speceq) .≈ B)

    B = (-0.003669740695888, 0.020567968301745, 0.072037115312651)
    @test all(get_Bfield(0.5,Float64(pi),pi/2,speceq) .≈ B)
end


@testset "Test 1 volume 2 B" begin
    B = (0, 0.038555184849609, 0.072710117678528)
    @test all(get_Bfield(0.0,0.0,0.0,speceq,2) .≈ B)

    B = (-0.002322619648770, 0.033036294198261, 0.075624851377662)
    @test all(get_Bfield(0.2,0.3,0.4,speceq,2) .≈ B)

    B = (0.002911725621285, 0.032303208066893, 0.068836461362085)
    @test all(get_Bfield(-0.2,-0.3,-0.4,speceq,2) .≈ B)

    B = (0.005074434713064, 0.043995961258377, 0.196623556328388)
    @test all(get_Bfield(0.5,Float64(pi),pi/2,speceq,2) .≈ B)
end




